# Sample build file
# @author Suren Konathala
# -----
image: node:10
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - echo "$(ls -la)"
            - npm install
            - npm install -g @angular/cli
            - ng build --prod
            - scp -r dist/traktrain-widget ubuntu@widget.traktrain.com:/var/www/html/