# Sample build file
# @author Suren Konathala
# -----
image: node:10
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - echo "$(ls -la)"
            - npm install
            - npm install -g @angular/cli
            - ng build --prod
            - scp -r dist/traktrain-widget ubuntu@widget.traktrain.com:/var/www/html
            - old="http://0.0.0.0:4200/"
            - new="http://widget.traktrain.com/index.html"
            - sed -i 's/${old}/${new}/g' src/iframe-test.html
            - scp -r src/iframe-test.html ubuntu@widget.traktrain.com:/var/www/html/traktrain-widget/
            